" Plugins and Vundle
set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim' " plugin manager
Plugin 'scrooloose/nerdtree'  " file tree
Plugin 'morhetz/gruvbox'      " favourite colorscheme
Plugin 'majutsushi/tagbar'    " tags, file structure overview
call vundle#end()             " required
filetype plugin indent on     " required

" Open Nerd tree if opening a directory
let g:NERDTreeHijackNetrw = 1
au VimEnter NERD_tree_1 enew | execute 'NERDTree '.argv()[0]

" Key mapping
map <C-n> :NERDTreeToggle<CR>
map <F8> :TagbarToggle<CR>

" 4 spaces instead of a tab
set tabstop=4 shiftwidth=4 expandtab
" 256 terminal colours:
set t_Co=256
" colorize sytanx
syntax on
" set text encoding to UTF8
set encoding=utf8
" set indent depending on file type
filetype plugin indent on
filetype plugin on
" make backspace work like most other apps
set backspace=2
" vsplit opens second file on the right instead of left
set splitright

set background=light
let g:gruvbox_contrast_light='soft'
silent colorscheme gruvbox

if &term =~# '^screen'
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

set termguicolors
