#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

merge_conf () {

    local i3_config=${HOME}/.config/i3/config
    local i3_config_base=${HOME}/.config/i3/base
    local i3_config_x240=${HOME}/.config/i3/x240
    local i3_config_workstation=${HOME}/.config/i3/workstation


    [[ $(hostname) = *"x240"* ]] \
        && cat ${i3_config_base} ${i3_config_x240} > ${i3_config} \
        || cat ${i3_config_base} ${i3_config_workstation} > ${i3_config}

}


merge_conf
exec i3
