#!/usr/bin/env zsh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


local i3_config_main=~/.config/i3/config
local i3_config_x240=~/.config/i3/config.x240
local i3_config_workstation=~/.config/i3/config.workstation

[[ $(hostname) = *"x240"* ]] \
    && cat ${i3_config_x240} > ${i3_config_main} \
    || cat ${i3_config_workstation} > ${i3_config_main}

exec i3
