#!/bin/sh
LOG_FILE="${HOME}/.log"
echo "[$(date --iso-8601=seconds)] ${0} sourced." >> ${LOG_FILE}

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

${HOME}/bin/i3-merge-conf.sh
${HOME}/bin/x-merge-conf.sh

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xsetroot -cursor_name left_ptr

exec i3-with-shmlog
