#!/usr/bin/env python3
from os import environ

import sarge

from utils import pango_format, percentage_colours

ICON = ''


def get_available_space() -> str:
    command = 'df -h / | awk "{print $4}" | tail -1'
    return sarge.get_stdout(command).strip('\n')


def get_disk_capacity() -> str:
    command = 'df -h / | awk "{print $2}" | tail -1'
    return sarge.get_stdout(command).strip('\n')


def get_user_percent() -> str:
    command = 'df -h / | awk "{print $5}" | tail -1'
    return sarge.get_stdout(command).strip('\n')


if __name__ == '__main__':
    try:
        block_button = environ.get('BLOCK_BUTTON')
        text = get_available_space()
        attributes = ''

        if block_button in ['1']:
            text += f' of {get_disk_capacity()} left'
        elif block_button in ['3']:
            percent_used = int(get_user_percent().strip('%'))
            color = list(percentage_colours())[percent_used]
            attributes = f'foreground="{color}"'
            text = f'{100 - percent_used}% free'

        whitespace = pango_format(' ', 'span', 'font="8"')

        msg = pango_format(f'{ICON}{whitespace}{text}', 'span', attributes)
    except Exception as e:
        msg = 'err', e
    print(msg)
