#!/usr/bin/env python3
import sarge
from utils import pango_format

ICON = ''


def get_free_space():
    command = 'df -h / | awk "{print $4}" | tail -1'
    return sarge.get_stdout(command).strip('\n')


if __name__ == '__main__':
    try:
        msg = pango_format(
                f'{ICON}{get_free_space()}', 'span', 'foreground=\'#928374\'')
    except Exception as e:
        msg = 'err', e
    print(msg)
