#!/usr/bin/env zsh

set -e

dotfiles_dir=${HOME}/.dotfiles/dotfiles
config_dir=${dotfiles_dir}/config/
utils_dir=${dotfiles_dir}/../utils/

echo -e "\nLinking dotfiles"
find ${dotfiles_dir} -maxdepth 1 -type f | while read -r file
do
    dotfile_in_repo="${file}"
    dotfile=${HOME}/".$(basename "${file}")"
    [ -f "${dotfile}" ] && rm "${dotfile}" \
        && echo -e "\t- Removed old ${dotfile}" \
        || echo -e "$\t- {dotfile} not present"

    ln -s "${dotfile_in_repo}" "${dotfile}" && echo -e "\t -Created a soft link to ${dotfile}"

done

echo -e "\nLinking scripts"
[[ -d "${HOME}/bin" ]] || mkdir "${HOME}/bin"
find ${utils_dir} -maxdepth 1 -type f -executable | while read -r executable
do
    script_in_repo="${executable}"
    script_in_home_bin=${HOME}/bin/"$(basename "${executable}")"
    [[ -f "${script_in_home_bin}"  ]] \
        && rm "${script_in_home_bin}" \
            && echo -e "\t- Removed ${script_in_home_bin}" \
            || echo -e "\t- ${script_in_home_bin} not present"

    ln -s "${script_in_repo}" "${script_in_home_bin}" \
        && echo -e "\t- Symlinked ${script_in_home_bin}"
done

echo -e "\nLinking config directories"
if [[ ! "$(uname -a)" = *"Darwin"* ]]; then
    ls -1 ${config_dir} | while read -r file
    do
        config_in_repo="${config_dir}/${file}"
        config=${HOME}/.config/"${file}"
        [ -e "${config}" ] && rm -rf ${config} \
            && echo -e "\t- Removed old ${config}" \
            || echo -e "\t- ${config} not present"
        ln -s "${config_in_repo}" "${config}" && echo -e "\t- Symlinked ${config}"
    done
fi
