bin/env python3
from colr import color

gruvbox_colors = dict(dark0_hard='',
                      dark0='',
                      dark0_soft='',
                      dark1='',
                      dark2='',
                      dark3='',
                      dark4='',
                      dark4_256='',
                      gray_245='',
                      gray_244='',
                      light0_hard='',
                      light0='',
                      light0_soft='',
                      light1='',
                      light2='',
                      light3='',
                      light4='',
                      light4_256='',
                      bright_red='',
                      bright_green='',
                      bright_yellow='',
                      bright_blue='',
                      bright_purple='',
                      bright_aqua='',
                      bright_orange='',
                      neutral_red='',
                      neutral_green='',
                      neutral_yellow='',
                      neutral_blue='',
                      neutral_purple='',
                      neutral_aqua='',
                      neutral_orange='',
                      faded_red='',
                      faded_green='',
                      faded_yellow='',
                      faded_blue='',
                      faded_purple='',
                      faded_aqua='',
                      faded_orange='')

for name, code in gruvbox_colors.items():
    print(f'{color(code, fore=code)}\t{name}')
